# Generated by Django 3.2.9 on 2021-12-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_asistencia_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.asignatura'),
        ),
    ]
